<?php
	require_once('includes/initses.php');
	require_once('includes/aftersetup.php');
	require_once('includes/mysqlcon.php');
	require_once('func/empluser.php');
	EmplUser\restrictPageToPositions($db,["superUser"]);
?>
<?php
	phpinfo();
?>